export enum UserRole {
  CITIZEN = 'CITIZEN',
  AUTHORITY = 'AUTHORITY'
}

export enum CameraStatus {
  ACTIVE = 'ACTIVE',
  OFFLINE = 'OFFLINE',
  MAINTENANCE = 'MAINTENANCE'
}

export enum PrivacyLevel {
  NONE = 'NONE', // Full raw feed
  BLUR_FACES = 'BLUR_FACES',
  ANONYMIZED = 'ANONYMIZED' // Stick figures / skeleton only
}

export interface Camera {
  id: string;
  name: string;
  location: string;
  ownerId: string;
  status: CameraStatus;
  privacySetting: PrivacyLevel;
  isShared: boolean;
  thumbnailUrl: string;
  videoUrl: string;
  lat: number;
  lng: number;
  locationVerified?: boolean; // Verified via Google Maps
  pendingAccessRequest?: boolean; // Authority has requested access
  smartTags?: string[]; // Tags generated by Gemini
  autoApprove?: boolean; // Owner pre-approves requests
}

export interface Incident {
  id: string;
  type: 'ACCIDENT' | 'THEFT' | 'FIRE' | 'CROWD' | 'TRAFFIC';
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  location: string;
  timestamp: string;
  cameraId: string;
  description: string;
  resolved: boolean;
}

export interface AnalysisResult {
  text: string;
  detectedObjects: string[];
  safetyScore: number;
  anprCandidates?: string[];
  privacyRecommendation?: boolean; // True if blur is recommended
  matchFound?: boolean; // True if target description matches
}

export interface Notification {
  id: string;
  title: string;
  message: string;
  time: string;
  read: boolean;
  type: 'ALERT' | 'INFO' | 'REQUEST';
}